dev/urls.py
from django.urls import path

from . import views

app_name = "dev"
urlpatterns = [
    path("", views.view_index, name="index"),
    path("headers", views.view_headers, name="headers"),
    path("log/<slug:service>/<slug:name>", views.view_log, name="log"),
]

guenthner_xyz/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, include

from general import plain_redirect, get_default_context, MySitemap
from . import views

error_urls = [path("", lambda *args: plain_redirect("/")),
              path("<int:status_code>", views.error_page), ]

account_urls = [path("login", LoginView.as_view(template_name="special/login.html",
                                                extra_context={**get_default_context(None),
                                                               "suppress_navbar": True,
                                                               "title": "Login to guenthner.xyz"}, ), name="login"),
                path("logout", LogoutView.as_view(template_name="special/logout.html",
                                                  extra_context={**get_default_context(None),
                                                                 "suppress_navbar": True,
                                                                 "title:": "You have been logged out"}, ),
                     name="logout")
    ,
                path("change-password",
                     PasswordChangeView.as_view(template_name="special/change_password.html",
                                                success_url=settings.PASSWORD_CHANGE_DONE_URL,
                                                extra_context={**get_default_context(None),
                                                               "suppress_navbar": True,
                                                               "title": "Change your password for guenthner.xyz"}, ),
                     name="change-password"),
                path("change-password/done",
                     PasswordChangeDoneView.as_view(template_name="special/change_password_done.html",
                                                    extra_context={**get_default_context(None),
                                                                   "suppress_navbar": True,
                                                                   "title": "Changing your password successful"}, ),
                     name="change-password-done")
                ]

indexed_routes = "index,math,eratosthenes,mandelbrot,paper,pretty,words,pictures,memes,creations,chat,cowsay,convolutions".split(",")

debug_static_routes = []

if settings.DEBUG:
    debug_static_routes = [path("js/<path:path>", views.view_debug_static("text/js")),
                           path("css/<path:path>", views.view_debug_static("text/css")), ]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(account_urls)),
    path("", include(debug_static_routes)),
    path("dev/", include("dev.urls")),
    path("private/", include("private.urls")),
    path("", include("root.urls")),
    path("error/", include(error_urls)),
    path("favicon.ico", lambda *args: plain_redirect("/images/site/icon.png", True)),
    MySitemap.with_path("sitemap.xml",
                        *[f"root:{i}" for i in indexed_routes]),

]

root/urls.py
from django.urls import path, include

from . import views

app_name = "root"

creations_urls = [path("", views.view_creations, name="creations"),
                  path("chat", views.view_chat, name="chat"),
                  path("cowsay", views.view_cowsay, name="cowsay"),
                  path("convolutions", views.view_convolutions, name="convolutions"),]

pretty_urls = [path("", views.view_pretty, name="pretty"),
               path("words", views.view_words, name="words"),
               path("pictures", views.view_pictures, name="pictures"), ]

math_urls = [path("", views.view_math, name="math"),
             path("paper", views.view_paper, name="paper"),
             path("mandelbrot", views.view_mandelbrot, name="mandelbrot"),
             path("eratosthenes", views.view_eratosthenes, name="eratosthenes")]

urlpatterns = [
    path("", views.view_index, name="index"),
    path("math/", include(math_urls)),
    path("pretty/", include(pretty_urls)),
    path("memes", views.view_memes, name="memes"),
    path("creations/", include(creations_urls)),
]

root/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import SET_NULL


class GlobalPermission(models.Model):
    # no fields needed; optional descriptive field
    name = models.CharField(max_length=128, blank=True)

    class Meta:
        verbose_name = "Global Permissions"
        verbose_name_plural = "Global Permissions"
        permissions = [
            ("admin", "Admin functions"),
        ]


class ChatMessage(models.Model):
    message = models.TextField()
    user = models.ForeignKey(User, on_delete=SET_NULL, null=True)
    time = models.DateTimeField(auto_now_add=True)

root/views.py
import math
import os
from datetime import datetime, UTC
from functools import reduce
from pathlib import Path

from django.conf import settings
from django.http import HttpRequest, HttpResponse
from django.views.decorators.cache import never_cache, cache_control
from django.views.decorators.http import condition

from general import default_render
from general.cowsay import run_cowsay
from root.models import ChatMessage

server_root = Path("/var/www/guenthner.xyz")


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_index(request: HttpRequest):
    return default_render(request, "root/index.html", {
        "first_name": "Jonathan",
        "last_name": "Günthner",
        "title": "Günthner's Webpage",
        "semester": int(math.ceil((datetime.now() - datetime(2024, 4, 1)).total_seconds() / (6 * 30 * 24 * 60 * 60))),
        "is_family": request.user.is_authenticated and request.user.has_perm("private.ffs")
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_pretty(request: HttpRequest):
    return default_render(request, "root/pretty/pretty.html", {
        "title": "Pretty Stuff I made"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_words(request: HttpRequest):
    return default_render(request, "root/pretty/words.html", {
        "title": "Pretty Words I wrote",
        "docs": os.listdir(server_root / "documents" / "stories"),
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_pictures(request: HttpRequest):
    return default_render(request, "root/pretty/pictures.html", {
        "title": "Pretty Pictures I made",
        "images": {"Sunlight.png": "A pretty abstract pictures with the theme sunlight",
                   "Sunlight - Pixelated.png": "The previous picture, but more pixelated",
                   "Blurry Sundown.png": "A blurry sundown recorded above a highway in Augsburg",
                   "Blurrier Sundown.png": "A blurrier version of the previous image"}
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_memes(request: HttpRequest):
    return default_render(request, "root/memes.html", {
        "title": "Memes",
        "images": os.listdir(server_root / "images" / "memes"),
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_creations(request: HttpRequest):
    return default_render(request, "root/creations/creations.html", {
        "title": "Creations"
    })


@never_cache
def view_cowsay(request: HttpRequest):
    return default_render(request, "root/creations/cowsay.html", {
        "title": "Cowsay",
        "output": run_cowsay()
    })


@never_cache
def view_chat(request: HttpRequest):
    error_msg = None
    messages = ChatMessage.objects.all()

    if request.method == "POST":
        if request.POST["message"] is None:
            error_msg = "No message received by server"
        elif request.POST["message"].strip() == "":
            error_msg = "Empty message"
        elif len(messages) > 0:
            last_msg_time = reduce(max, [m.time for m in messages])
            delta = (datetime.now(tz=UTC) - last_msg_time).total_seconds()
            if delta < 10:
                error_msg = "Wait at least 10 seconds between messages"

        if error_msg is None:
            ChatMessage.objects.create(user=request.user if request.user.is_authenticated else None,
                                       message=request.POST["message"], )

        if request.POST.get("FROM_JS", False):
            return HttpResponse(error_msg, status=200 if error_msg is None else 400)

    return default_render(request, "root/creations/chat.html", {
        "title": "Chat",
        "messages": messages,
        "error_msg": error_msg})


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_convolutions(request: HttpRequest):
    return default_render(request, "root/creations/convolutions.html", {
        "title": "Convolutions",
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_math(request: HttpRequest):
    return default_render(request, "root/math/math.html", {
        "title": "The Math-Corner"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_paper(request: HttpRequest):
    return default_render(request, "root/math/paper.html", {
        "title": "Paper"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_mandelbrot(request: HttpRequest):
    return default_render(request, "root/math/mandelbrot.html", {
        "title": "Mandelbrot"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_eratosthenes(request: HttpRequest):
    return default_render(request, "root/math/eratosthenes.html", {
        "title": "Eratosthenes"
    })

root/templates/root/creations/chat.html
{% extends "base.html" %}
{% load utils %}
{% block head %}
    {{ "A primitive global chat" | add_description }}
    {% load_css "navigation" %}
    {% load_js "chat" %}
    <style>
        form * {
            display: block;
        }

        * {
            scroll-behavior: smooth;
        }

        .accessibility-only {
            position: absolute;
            left: -10000px;
            top: auto;
            width: 1px;
            height: 1px;
            overflow: hidden;
        }

        .message-header {
            display: flex;
        }

        .message {
            margin: 1em;
            padding: 1em;
            border: #aaa 3px solid;
            border-radius: 1em;
            background: #f7f7f7;
        }

        .admin {
            flex-grow: 1;
            color: red;
            text-align: right;
        }

        .admin-message {
            border-color: red;
        }

        #message-input {
            width: 100%;
            height: 5em;
        }

        sup {
            vertical-align: top;
            margin-right: 0.2em;
        }

        .inline {
            display: inline;
        }

        #error-output {
            color: darkred;
        }

        .hover-button {
            display: block;
            position: sticky;
            font-family: sans-serif;
            cursor: pointer;

            margin-top: 0.3em;
            background: linear-gradient(90deg, white 0%, #ddd 100px, #ddd calc(100% - 100px), white 100%);
            border: none;

            text-align: center;
        }

        .hover-button:hover {
            background: linear-gradient(90deg, white 0%, #bbb 100px, #bbb calc(100% - 100px), white 100%);
        }

        #reload-button {
            top: 0;
        }

        #scroll-button {
            bottom: 0;
        }
    </style>
{% endblock %}
{% block content %}
    <h3>A primitive global Chat</h3>
    <div>
        You are visible as {{ request.user }}
    </div>
    <div id="reload-button" class="show-on-js hover-button">Load newest messages</div>
    <div style="margin: 3em">
        {% for msg in messages %}
            <div class='{% if msg.user.is_staff %} admin-message {% endif %} message'>
                <div class='message-header'>
                    <span>{{ msg.user|default:"Anonymous" }} - <span
                            style='display: inline-block'>{{ msg.time }} ({{ msg.time|timesince }} ago)</span></span>
                    {% if msg.user.is_staff %}
                        <span class='admin'>admin</span>
                    {% endif %}
                </div>
                <div>
                    {{ msg.message|linebreaks }}
                </div>
            </div>
        {% endfor %}
    </div>
    <div id="scroll-button" class="show-on-js hover-button">Scroll to bottom</div>
    <div style="margin-bottom: 5em">
        <form id="message-form" method="post" action="{% url "root:chat" %}">
            {% csrf_token %}
            <label for="message-input" class="accessibility-only">
                Message
            </label>
            <textarea name="message" id="message-input" class="message"
                      placeholder="Enter your message here"></textarea>
            <button class="inline">Send</button>
            <span class="inline" id="error-output">{{ error_msg|default:"" }}</span>
        </form>
    </div>
{% endblock %}

root/templates/root/creations/convolutions.html
{% extends "base.html" %}
{% load utils %}
{% block head %}
    {{ ""|add_description }}
    {% load_css "navigation" %}

    <!-- KaTeX here -->
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.css"
          integrity="sha384-2+1yEhq+grOgz1BVYTZPyTlMXrDxnjN1By9/ba94JqJhva6wFm2Hb+URQX53v" crossorigin="anonymous">
    <script id="katex-script" defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.js"
            integrity="sha384-C5yZTsgLOfuizO9kb+hrB8uSBwwvZ4yenKWU0KmWl+7bkL6Tph/KbcOa3S4zdoRE"
            crossorigin="anonymous"></script>-->

    <style>
        .horiz-flex {
            width: 100%;
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-content: space-evenly;
        }

        .main-canvas {
            width: 40vw;
            height: 40vw;
        }

        canvas {
            margin: 20px;
            image-rendering: pixelated;
            border: 10px double black;
            border-radius: 10px;
        }

        #kernel_canvas {
            width: 10vw;
            height: 10vw;
        }

        label {
            display: flex;
            flex-direction: column;
        }

        .controls {
            display: flex;
            flex-direction: column;
        }

        .color-view {
            width: 0;
            height: 0;
            border: 10px solid black;
            border-radius: 10px;
            align-self: center;
            margin: 10px;
        }
    </style>

    <script>
        window.addEventListener("alpine:init", () => {
            Alpine.store("brush", Alpine.reactive({
                "value": 0.5,
                "radius": 1.0
            }));
        });
    </script>

    {% load_alpine %}
    {% load_js "util/my_webgl" extra_args="defer" %}
    {% load_js "convolutions" extra_args="defer" %}
    {% load_js "util/draw_on_canvas" extra_args="defer" %}
{% endblock %}
{% block content_container %}
    {% include "navigation_bar.html" %}

    <main>
        <div class="horiz-flex">
            <canvas id="in_canvas" class="main-canvas drawable">Canvas seem to be unsupported here :(</canvas>
            <canvas id="out_canvas" class="main-canvas">Canvas seem to be unsupported here :(</canvas>
        </div>
        <div class="horiz-flex">
            <canvas id="kernel_canvas" class="drawable">Canvas seem to be unsupported here :(</canvas>
            <div class="controls">
                <label>
                    <span x-data x-text='"Width: " + Number.parseFloat($store.brush.radius).toFixed(2)'></span>
                    <input type="range" x-data x-model.number="$store.brush.radius" min="1" max="10" step="0.05"
                           @keyup.window.p="$store.brush.radius = 1">
                </label>
                <label>
                    <span x-data x-text='"Value: " + Number.parseFloat($store.brush.value).toFixed(2)'></span>
                    <input type="range" x-data x-model.number="$store.brush.value" min="0" max="1" step="0.05"
                           @keyup.window.w="$store.brush.value = 1"
                           @keyup.window.b="$store.brush.value = 0"
                           @keyup.window.g="$store.brush.value = 0.5">
                </label>
                <div class="color-view">
                </div>
            </div>
        </div>
        <div class="paper-center">
            <h1>Information</h1>

            Now, I won't explain what convolutions are or what convolutions are in the context of image processing.
            This is just a fun toy for drawing your own image kernels and applying them to self drawn images.

            The three canvases in order are:
            <ol>
                <li>Input Canvas (Can be drawn on)</li>
                <li>Output Canvas (Shows the result of applying the kernel to the input)</li>
                <li>Kernel Canvas (That's the small one)</li>
            </ol>

            <h2>How to draw?</h2>

            Just click and drag on the canvas on the left or on the bottom. The value slider moves the color from black
            (0) to white (1).

            <h2>What do the colors mean?</h2>

            On the input canvas the numerical meanings of the colors are from black (0) to white (1), but on the kernel
            canvas the colors go from black (-1) over gray (0) to white (1). This means that the identity kernel is
            mostly gray.
            This can be used to create kernels with negative entries.
        </div>
    </main>
{% endblock %}

root/templates/root/creations/cowsay.html
{% extends "base.html" %}
{% load utils %}
{% block head %}
    {{ "The output of the fortune command piped into the cowsay command"|add_description }}
    {% load_css "navigation" %}
    <style>
        div.center {
            text-align: center;
            padding-top: 50px;
        }

        pre.center {
            display: inline-block;
            text-align: left;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="center">
        <pre class="center">{{ output }}</pre>

    </div>
    <div class="center">
        <pre class="center">fortune | cowsay</pre>
    </div>
{% endblock %}

root/templates/root/creations/creations.html
{% extends "base.html" %}
{% load utils %}
{% block head %}
    {{ "My creations (mostly just minor funny little web apps)"|add_description }}
    {% load_css "navigation" %}
{% endblock %}
{% block content %}
    <h1>My creations</h1>
    <ul class="navigation">
        <li><a href="{% url "root:chat" %}">Chat</a></li>
        <li><a href="{% url "root:cowsay" %}">Cowsay</a></li>
        <li><a href="{% url "root:convolutions" %}">Convolutions</a></li>
    </ul>
{% endblock %}