dev/urls.py
from django.urls import path

from . import views

app_name = "dev"
urlpatterns = [
    path("", views.view_index, name="index"),
    path("headers", views.view_headers, name="headers"),
    path("log/<slug:service>/<slug:name>", views.view_log, name="log"),
]

guenthner_xyz/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, include

from general import plain_redirect, get_default_context, MySitemap
from . import views

error_urls = [path("", lambda *args: plain_redirect("/")),
              path("<int:status_code>", views.error_page), ]

account_urls = [path("login", LoginView.as_view(template_name="special/login.html",
                                                extra_context={**get_default_context(None),
                                                               "suppress_navbar": True,
                                                               "title": "Login to guenthner.xyz"}, ), name="login"),
                path("logout", LogoutView.as_view(template_name="special/logout.html",
                                                  extra_context={**get_default_context(None),
                                                                 "suppress_navbar": True,
                                                                 "title:": "You have been logged out"}, ),
                     name="logout")
    ,
                path("change-password",
                     PasswordChangeView.as_view(template_name="special/change_password.html",
                                                success_url=settings.PASSWORD_CHANGE_DONE_URL,
                                                extra_context={**get_default_context(None),
                                                               "suppress_navbar": True,
                                                               "title": "Change your password for guenthner.xyz"}, ),
                     name="change-password"),
                path("change-password/done",
                     PasswordChangeDoneView.as_view(template_name="special/change_password_done.html",
                                                    extra_context={**get_default_context(None),
                                                                   "suppress_navbar": True,
                                                                   "title": "Changing your password successful"}, ),
                     name="change-password-done")
                ]

indexed_routes = "index,math,eratosthenes,mandelbrot,paper,pretty,words,pictures,memes,creations,chat,cowsay,convolutions".split(",")

debug_static_routes = []

if settings.DEBUG:
    debug_static_routes = [path("js/<path:path>", views.view_debug_static("text/js")),
                           path("css/<path:path>", views.view_debug_static("text/css")), ]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(account_urls)),
    path("", include(debug_static_routes)),
    path("dev/", include("dev.urls")),
    path("private/", include("private.urls")),
    path("", include("root.urls")),
    path("error/", include(error_urls)),
    path("favicon.ico", lambda *args: plain_redirect("/images/site/icon.png", True)),
    MySitemap.with_path("sitemap.xml",
                        *[f"root:{i}" for i in indexed_routes]),

]

root/urls.py
from django.urls import path, include

from . import views

app_name = "root"

creations_urls = [path("", views.view_creations, name="creations"),
                  path("chat", views.view_chat, name="chat"),
                  path("cowsay", views.view_cowsay, name="cowsay"),
                  path("convolutions", views.view_convolutions, name="convolutions"),]

pretty_urls = [path("", views.view_pretty, name="pretty"),
               path("words", views.view_words, name="words"),
               path("pictures", views.view_pictures, name="pictures"), ]

math_urls = [path("", views.view_math, name="math"),
             path("paper", views.view_paper, name="paper"),
             path("mandelbrot", views.view_mandelbrot, name="mandelbrot"),
             path("eratosthenes", views.view_eratosthenes, name="eratosthenes")]

urlpatterns = [
    path("", views.view_index, name="index"),
    path("math/", include(math_urls)),
    path("pretty/", include(pretty_urls)),
    path("memes", views.view_memes, name="memes"),
    path("creations/", include(creations_urls)),
]

root/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import SET_NULL


class GlobalPermission(models.Model):
    # no fields needed; optional descriptive field
    name = models.CharField(max_length=128, blank=True)

    class Meta:
        verbose_name = "Global Permissions"
        verbose_name_plural = "Global Permissions"
        permissions = [
            ("admin", "Admin functions"),
        ]


class ChatMessage(models.Model):
    message = models.TextField()
    user = models.ForeignKey(User, on_delete=SET_NULL, null=True)
    time = models.DateTimeField(auto_now_add=True)

root/views.py
import math
import os
from datetime import datetime, UTC
from functools import reduce
from pathlib import Path

from django.conf import settings
from django.http import HttpRequest, HttpResponse
from django.views.decorators.cache import never_cache, cache_control
from django.views.decorators.http import condition

from general import default_render
from general.cowsay import run_cowsay
from root.models import ChatMessage

server_root = Path("/var/www/guenthner.xyz")


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_index(request: HttpRequest):
    return default_render(request, "root/index.html", {
        "first_name": "Jonathan",
        "last_name": "Günthner",
        "title": "Günthner's Webpage",
        "semester": int(math.ceil((datetime.now() - datetime(2024, 4, 1)).total_seconds() / (6 * 30 * 24 * 60 * 60))),
        "is_family": request.user.is_authenticated and request.user.has_perm("private.ffs")
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_pretty(request: HttpRequest):
    return default_render(request, "root/pretty/pretty.html", {
        "title": "Pretty Stuff I made"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_words(request: HttpRequest):
    return default_render(request, "root/pretty/words.html", {
        "title": "Pretty Words I wrote",
        "docs": os.listdir(server_root / "documents" / "stories"),
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_pictures(request: HttpRequest):
    return default_render(request, "root/pretty/pictures.html", {
        "title": "Pretty Pictures I made",
        "images": {"Sunlight.png": "A pretty abstract pictures with the theme sunlight",
                   "Sunlight - Pixelated.png": "The previous picture, but more pixelated",
                   "Blurry Sundown.png": "A blurry sundown recorded above a highway in Augsburg",
                   "Blurrier Sundown.png": "A blurrier version of the previous image"}
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_memes(request: HttpRequest):
    return default_render(request, "root/memes.html", {
        "title": "Memes",
        "images": os.listdir(server_root / "images" / "memes"),
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_creations(request: HttpRequest):
    return default_render(request, "root/creations/creations.html", {
        "title": "Creations"
    })


@never_cache
def view_cowsay(request: HttpRequest):
    return default_render(request, "root/creations/cowsay.html", {
        "title": "Cowsay",
        "output": run_cowsay()
    })


@never_cache
def view_chat(request: HttpRequest):
    error_msg = None
    messages = ChatMessage.objects.all()

    if request.method == "POST":
        if request.POST["message"] is None:
            error_msg = "No message received by server"
        elif request.POST["message"].strip() == "":
            error_msg = "Empty message"
        elif len(messages) > 0:
            last_msg_time = reduce(max, [m.time for m in messages])
            delta = (datetime.now(tz=UTC) - last_msg_time).total_seconds()
            if delta < 10:
                error_msg = "Wait at least 10 seconds between messages"

        if error_msg is None:
            ChatMessage.objects.create(user=request.user if request.user.is_authenticated else None,
                                       message=request.POST["message"], )

        if request.POST.get("FROM_JS", False):
            return HttpResponse(error_msg, status=200 if error_msg is None else 400)

    return default_render(request, "root/creations/chat.html", {
        "title": "Chat",
        "messages": messages,
        "error_msg": error_msg})


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_convolutions(request: HttpRequest):
    return default_render(request, "root/creations/convolutions.html", {
        "title": "Convolutions",
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_math(request: HttpRequest):
    return default_render(request, "root/math/math.html", {
        "title": "The Math-Corner"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_paper(request: HttpRequest):
    return default_render(request, "root/math/paper.html", {
        "title": "Paper"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_mandelbrot(request: HttpRequest):
    return default_render(request, "root/math/mandelbrot.html", {
        "title": "Mandelbrot"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_eratosthenes(request: HttpRequest):
    return default_render(request, "root/math/eratosthenes.html", {
        "title": "Eratosthenes"
    })

root/templates/root/math/eratosthenes.html
{% extends "base.html" %}
{% load utils %}
{% block head %}
    {{ "A visually pleasing implementation of the sieve of Eratosthenes, a mathematical method for finding prime numbers."|add_description }}
    {% load_css "navigation" %}
    {% load_css "eratosthenes" %}
    {% load_js "eratosthenes" extra_args="async" %}
    <!-- KaTeX here -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.css"
          integrity="sha384-o3WH+1yEhq+grOgz1BVYTZPyTlMXrDxnjN1By9/ba94JqJhva6wFm2Hb+URQX53v" crossorigin="anonymous">
    <script id="katex-script" defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.js"
            integrity="sha384-C5yZTsgLOfuizO9kb+hrB8uSBwwvZ4yenKWU0KmWl+7bkL6Tph/KbcOa3S4zdoRE"
            crossorigin="anonymous"></script>
    <style>
        div {
            margin-bottom: 0.34em;
        }

        .header-like {
            margin-top: 1em;
            margin-bottom: 0.4em;
        }
    </style>
{% endblock %}
{% block content %}
    <h1>The Sieve of Eratosthenes</h1>
    <div>
        <div class="header-like"><b>Controls</b></div>
        <div>
            <label for="table-width">Width</label>
            <input id="table-width" type="text">
            <label for="table-height">Height</label>
            <input id="table-height" type="text">
        </div>
        <div>
            <button id="create-table-button">Create Table</button>
        </div>
        <div data-setting-hidden="1">
            <div class="header-like fade-on-hide setting-visibility-toggle"><b>Constellation Settings</b></div>
            <div class="disappear-on-hide">(For a basic explanation refer to <a
                    href="https://github.com/Askhor/NotesAboutPrimeConstellations/">Notes about prime constellations</a>)
            </div>
            <div id="constellation-settings-container" class="disappear-on-hide">

            </div>
        </div>
    </div>
    <div id="number-info">

    </div>
    <div>
        <canvas id="table-root">
            Well, canvases don't work here.....
        </canvas>
    </div>
    <div data-setting-hidden="1">
        <div class="header-like fade-on-hide setting-visibility-toggle"><b>Cheat Sheet</b></div>
        <div id="constellation-settings-container" class="disappear-on-hide">
            <div>
                Number represented by cell <span class="latex">(x,y)</span> is <span
                    class="latex">x + y*\text{width}</span>.
            </div>
            <div>Color of cell for <span class="latex">n</span> is
                <div style="display: inline-block; vertical-align: top">
                    <ul style="display: inline">
                        <li><b style="color: #900">A color</b> if the number is a multiple of a lmb-marked number</li>
                        <li><b>Black/dark grey</b> if the number is rmb-marked depending on parity</li>
                        <li><b>Light grey</b> if the number is 0,1 or a multiple of a rmb-marked number</li>
                        <li><b>White</b> otherwise</li>
                    </ul>
                </div>
            </div>
            <div>
                Text will appear on lmb-marked numbers.
            </div>
        </div>
    </div>
    <script>
        document.getElementById("katex-script").addEventListener("load", _ => {
            console.log("Rendering LaTeX");
            document.querySelectorAll(".latex").forEach(el => {
                katex.render(el.textContent, el);
            })
        })
    </script>
{% endblock %}

root/templates/root/math/mandelbrot.html
{% extends "base.html" %}
{% load utils %}
{% block head %}
    {{ "A fast simulation of the mandelbrot set using WebGL. The quality erodes as you zoom in too much."|add_description }}
    {% load_css "navigation" %}
    <link rel="stylesheet" href="{{ schost }}/css/hide_on_mobile.css"
          media="screen and (max-width:600px)">
    <!-- KaTeX here -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.css"
          integrity="sha384-o3WH+1yEhq+grOgz1BVYTZPyTlMXrDxnjN1By9/ba94JqJhva6wFm2Hb+URQX53v" crossorigin="anonymous">
    <script id="katex-script" defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.js"
            integrity="sha384-C5yZTsgLOfuizO9kb+hrB8uSBwwvZ4yenKWU0KmWl+7bkL6Tph/KbcOa3S4zdoRE"
            crossorigin="anonymous"></script>
    <style>
        #gl-canvas {
            position: absolute;
            top: 0;
            left: 0;
            z-index: 0;
        }

        input {
            display: block;
        }

        #content-container {
            cursor: default;
            position: absolute;
            top: 0;
            left: 0;
            width: 100vw;
        }

        .glow {
            text-shadow: 0 0 1px white;
        }

        /*.glow img {*/
        /*    background: #FFF9;*/
        /*    box-shadow: 0 0 10px #FFF9;*/
        /*}*/

        img {
            pointer-events: none;
        }

        html {
            overscroll-behavior-y: none;
        }

        body {
            overscroll-behavior-y: none;
        }

        #download-button {
            position: absolute;
            top: 20px;
            right: 200px;
            z-index: 1;
            background: grey;
            border: 2px white;
            border-radius: 1px
        }

        #download-button:hover {
            background: darkgray;
        }
    </style>
{% endblock %}
{% block content_container %}
    {% include "navigation_bar.html" %}
    <div class="glow" style="position: absolute; top: 20px; right: 20px; z-index: 1">
        <label for="iter-count">Iteration Count</label><input id="iter-count" type="range">
        <label for="pulsation">Pulsation</label><input id="pulsation" type="range">
        <label for="start-x">Start X</label><input id="start-x" type="range">
        <label for="start-y">Start Y</label><input id="start-y" type="range">
        <label for="split-amount">Split Amount</label><input id="split-amount" type="range">
        <label for="split-direction">Split Direction</label><input id="split-direction" type="range">
        <label for="zoom">Zoom</label><input id="zoom" type="range">
    </div>

    <button id="download-button">
        <img src="{{ schost }}/images/site/download_1.svg"
             alt="Download">
    </button>

    <canvas id="gl-canvas"></canvas>

    <div id="content-container">
        <main class="glow">
            <h1>The Mandelbrot Set</h1>

            <div class="hide-on-mobile latex">
                \begin{align*}
                f_c(k+1) &= f_c(k)^2 + c \\\\
                f_c(0) &= \text{Start} \\\\
                \set{ z \in \mathbb{C} \mid &\lim_{k \to \infty} f_z(k) < \infty }
                \end{align*}
            </div>
            <label for="debug-output"></label><textarea id="debug-output" readonly
                                                        style="display: none; width: 700px; resize: none;"></textarea>
        </main>
    </div>

    <script>
        document.getElementById("katex-script").addEventListener("load", _ => {
            console.log("Rendering LaTeX");
            document.querySelectorAll(".latex").forEach(el => {
                katex.render(el.textContent, el, {displayMode: true});
            })
        })
    </script>
    {% load_js "mandelbrot" extra_args="defer" %}
{% endblock %}

root/templates/root/math/math.html
{% extends "base.html" %}
{% load utils %}
{% block head %}
    {{ "All my math related internet content"|add_description }}
    {% load_css "navigation" %}
    <style>
        .image-container {
            position: absolute;
            z-index: 1;
            top: 0;
            right: 0;
            width: 60vw;
        }

        .image-container img {
            width: 100%;
        }

        #main-container {
            min-height: calc(60vw * 1.618);
        }

        main {
            position: relative;
            z-index: 2;
        }
    </style>
{% endblock %}
{% block pre %}
    <div class="image-container">
        <img src="{{ schost }}/images/site/math/mandel.png" alt="Mandelbrot-Set">
        <div class="phantom-footer"></div>
    </div>
{% endblock %}
{% block content %}
    <h1>The Math-Corner</h1>
    <ul class="navigation">
        <li><a href="{% url "root:paper" %}">Paper</a></li>
        <li><a href="{% url "root:mandelbrot" %}">Mandelbrot</a></li>
        <li><a href="{% url "root:eratosthenes" %}">Eratosthenes</a></li>
    </ul>
{% endblock %}

root/templates/root/math/paper.html
{% extends "base.html" %}
{% load utils %}
{% block head %}
    {{ "A list of all the papers that I have written"|add_description }}
    {% load_css "navigation" %}
    <!-- KaTeX here -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.css"
          integrity="sha384-o3WH+1yEhq+grOgz1BVYTZPyTlMXrDxnjN1By9/ba94JqJhva6wFm2Hb+URQX53v" crossorigin="anonymous">
    <script id="katex-script" defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.js"
            integrity="sha384-C5yZTsgLOfuizO9kb+hrB8uSBwwvZ4yenKWU0KmWl+7bkL6Tph/KbcOa3S4zdoRE"
            crossorigin="anonymous"></script>
{% endblock %}
{% block content %}
    <h1>My Paper</h1>
    <ul class="navigation">
        <li>
            <a href="https://{{ request.get_host }}/documents/paper/Orbits.pdf">Die Anzahl an Orbits unter
                Multiplikation modulo eine Zahl</a>
            <div>This paper (in German) proves—amongst other things—the following formula:
                <span class="latex">\newcommand{\ord}{\mathop{\text{ord}}} \ord_{p^k}(m) = \ord_{p}(m) \cdot p^{\max(0, k - k_0 + 1)}</span>
            </div>
        </li>
        <li>
            <a href="https://github.com/Askhor/Order-Formula/blob/main/Order%20Formula.pdf">work in progress on
                github</a>
            <div>
                This paper investigates the formula from the previous paper more closely and derives inequalities for
                perfect numbers.
            </div>
        </li>
    </ul>

    <script>
        document.getElementById("katex-script").addEventListener("load", _ => {
            console.log("Rendering LaTeX");
            document.querySelectorAll(".latex").forEach(el => {
                katex.render(el.textContent, el, {throwOnError: false});
            })
        })
    </script>
{% endblock %}