dev/urls.py
from django.urls import path

from . import views

app_name = "dev"
urlpatterns = [
    path("", views.view_index, name="index"),
    path("headers", views.view_headers, name="headers"),
    path("log/<slug:service>/<slug:name>", views.view_log, name="log"),
]

guenthner_xyz/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, include

from general import plain_redirect, get_default_context, MySitemap
from . import views

error_urls = [path("", lambda *args: plain_redirect("/")),
              path("<int:status_code>", views.error_page), ]

account_urls = [path("login", LoginView.as_view(template_name="special/login.html",
                                                extra_context={**get_default_context(None),
                                                               "suppress_navbar": True,
                                                               "title": "Login to guenthner.xyz"}, ), name="login"),
                path("logout", LogoutView.as_view(template_name="special/logout.html",
                                                  extra_context={**get_default_context(None),
                                                                 "suppress_navbar": True,
                                                                 "title:": "You have been logged out"}, ),
                     name="logout")
    ,
                path("change-password",
                     PasswordChangeView.as_view(template_name="special/change_password.html",
                                                success_url=settings.PASSWORD_CHANGE_DONE_URL,
                                                extra_context={**get_default_context(None),
                                                               "suppress_navbar": True,
                                                               "title": "Change your password for guenthner.xyz"}, ),
                     name="change-password"),
                path("change-password/done",
                     PasswordChangeDoneView.as_view(template_name="special/change_password_done.html",
                                                    extra_context={**get_default_context(None),
                                                                   "suppress_navbar": True,
                                                                   "title": "Changing your password successful"}, ),
                     name="change-password-done")
                ]

indexed_routes = "index,math,eratosthenes,mandelbrot,paper,pretty,words,pictures,memes,creations,chat,cowsay,convolutions".split(",")

debug_static_routes = []

if settings.DEBUG:
    debug_static_routes = [path("js/<path:path>", views.view_debug_static("text/js")),
                           path("css/<path:path>", views.view_debug_static("text/css")), ]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(account_urls)),
    path("", include(debug_static_routes)),
    path("dev/", include("dev.urls")),
    path("private/", include("private.urls")),
    path("", include("root.urls")),
    path("error/", include(error_urls)),
    path("favicon.ico", lambda *args: plain_redirect("/images/site/icon.png", True)),
    MySitemap.with_path("sitemap.xml",
                        *[f"root:{i}" for i in indexed_routes]),

]

private/urls.py
from django.http import HttpResponsePermanentRedirect
from django.urls import path, include

from . import views

app_name = "private"

ffs_urls = [path("", views.view_index, name="ffs"),
            path("ffs-info", views.view_ffs_info, name="ffs-info"),
            path("<str:api>/", views.view_api, name="api"),
            path("<str:api>/<path:path>", views.view_api, name="api"), ]

urlpatterns = [path("ffs/", include(ffs_urls)),
               path("", lambda *a: HttpResponsePermanentRedirect("ffs/")), ]

private/models.py
import logging
import re
from pathlib import Path

from django.db import models
from django.utils import timezone

from general import UserError

log = logging.getLogger("my")


class GlobalPermission(models.Model):
    # no fields needed; optional descriptive field
    name = models.CharField(max_length=128, blank=True)

    class Meta:
        verbose_name = "Global Permissions"
        verbose_name_plural = "Global Permissions"
        permissions = [
            ("ffs", "FFS")
        ]


class FilePacket(models.Model):
    NEW = "NEW"
    FAILED = "FAILED"
    PENDING = "PENDING"
    STORED = "STORED"

    hsh = models.CharField(max_length=128, blank=True, primary_key=True)
    file = models.CharField(max_length=128, null=True, blank=True, default=None)
    status = models.CharField(choices={s: s for s in [NEW, FAILED, PENDING, STORED]}, max_length=20,
                              default=NEW)
    upload_date = models.DateTimeField(default=timezone.now)
    last_used = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        self.last_used = timezone.now()
        super().save(*args, **kwargs)

    @classmethod
    def status_for(cls, hsh):
        try:
            return cls.objects.get(hsh=hsh).status
        except cls.DoesNotExist:
            return FilePacket.PENDING


class PermissionsRule(models.Model):
    rule = models.CharField(max_length=128, primary_key=True)
    users = models.CharField(max_length=128)
    is_template = models.BooleanField(default=False)

    def get_rule(self):
        if not self.is_template:
            return self.rule

        return self.rule.replace("$USER", "(?P<user>$SEG)").replace("$SEG", "[a-zA-Z0-9._ -]*")

    def matches(self, path: Path) -> bool:
        regex = re.compile(self.get_rule())
        return regex.match(str(path))

    @staticmethod
    def normalise(path: Path):
        path = str(path)
        if "../" in path:
            raise UserError("Please don't have \"..\" in your paths")
        path = path.replace("./", "")
        return path

    def user_allowed(self, path: Path, username: str):
        path = self.normalise(path)

        if (match := self.matches(path)) is None:
            return True

        user_re = self.users

        if self.is_template:
            try:
                user_re = user_re.replace("$USER", match.groupdict()["user"])
            except KeyError:
                pass

        return re.match(user_re, username) is not None

    def __str__(self):
        return f"{self.rule}: {self.users}"

private/views.py
import datetime
import hashlib
import json
import logging
import os
import re
import shutil
import zipfile
from pathlib import Path

import PIL
from PIL import Image
from PIL.ExifTags import TAGS
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpRequest, HttpResponse, FileResponse, JsonResponse, \
    HttpResponseServerError, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.cache import cache_control, never_cache
from django.views.decorators.http import require_http_methods, condition, require_safe
from django.views.decorators.vary import vary_on_headers

from general import default_render, exception_to_response, UserError, get_mime_type
from guenthner_xyz import settings
from private.icons import img_file_icon
from private.models import FilePacket, PermissionsRule

log = logging.getLogger("my")

fs_root = settings.FFS_FS_ROOT
file_packet_cache = settings.FFS_FILE_PACKET_CACHE

img_mime = re.compile("image/.+")
video_mime = re.compile("video/.+")


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda request: str(request.user))
@login_required
@permission_required("private.ffs")
def view_index(request: HttpRequest):
    return default_render(request, "private/index.html", {
        "title": "FFS"
    })


def require_path_exists(func):
    def wrapper(request: HttpRequest, path: Path):
        if not (fs_root / path).exists():
            if request.method == "HEAD":
                return HttpResponse(status=404, content_type="text/plain; charset=utf-8")
            return HttpResponse(f"File {path} does not exist", status=404,
                                content_type="text/plain; charset=utf-8")
        return func(request, path)

    return wrapper


def check_path(request: HttpRequest, path: Path):
    if path.is_absolute():
        raise UserError("Path must not be absolute and it really looks like that")


def check_permissions(request: HttpRequest, path: Path):
    for rule in PermissionsRule.objects.all():
        if not rule.user_allowed(path, str(request.user)):
            return HttpResponse(f"You are not allowed to view this location.\n"
                                f"You have been blocked by the rule:\n"
                                f"{rule}", status=403, content_type="text/plain; charset=utf-8")

    return None


def get_path_last_mod(request, path: Path):
    full_path = fs_root / path
    if not full_path.exists():
        return None
    return datetime.datetime.fromtimestamp(full_path.stat().st_mtime)


def get_path_etag(request, path: Path):
    full_path = fs_root / path

    if not full_path.exists():
        return None

    hsh = hashlib.sha256()

    if full_path.is_file():
        hsh.update(str(full_path.stat().st_mtime).encode())
        hsh.update(str(full_path.stat().st_size).encode())
    else:
        for f in full_path.iterdir():
            hsh.update(f.name.encode())

    return hsh.hexdigest()


class MediaView:
    def __init__(self, keyword):
        self.keyword = keyword
        self.re_mime = re.compile(f"{keyword}/.+")

    def matches(self, string):
        return self.re_mime.fullmatch(string)

    def view(self, request: HttpRequest, path: Path):
        return default_render(request, f"private/{self.keyword}_view.html", {
            "path": path,
            "name": path.name,
            "parent": path.parent
        })


media_views = list(map(MediaView, ["image", "video", "audio"]))


@require_http_methods(["GET"])
@condition(etag_func=get_path_etag, last_modified_func=get_path_last_mod)
def api_files(request: HttpRequest, path: Path):
    full_path = fs_root / path
    extra_context = {}

    if not full_path.exists():
        template_name = "file_404"
        title_msg = "does not exist"
    elif full_path.is_file():
        mime_type = get_mime_type(full_path)
        if mime_type == "text/plain":
            return HttpResponseRedirect(reverse("private:api", kwargs={"api": "notepad", "path": path}))

        for mv in media_views:
            if mv.matches(mime_type):
                return mv.view(request, path)

        return api_raw.call(request, path)
    else:
        template_name = "files"
        title_msg = "Directory"
        files = list(full_path.iterdir())
        files.sort()
        extra_context = {"net_block_size": settings.FFS_NET_BLOCK_SIZE}

    return default_render(request, f"private/{template_name}.html", {
        "title": f"{path}: {title_msg}", **extra_context,
        "path": path,
    })


@require_http_methods(["GET"])
@require_path_exists
@condition(etag_func=get_path_etag, last_modified_func=get_path_last_mod)
def api_icon(request: HttpRequest, path: Path):
    try:
        return FileResponse(open(img_file_icon(path), "rb"))
    except RuntimeError:
        return HttpResponse(status=500)


def populate_info_dict(info, path: Path, level):
    mime = get_mime_type(path)

    info[str(path.relative_to(fs_root))] = {
        "path": str(path.relative_to(fs_root)),
        "name": path.name,
        "size": path.stat().st_size,
        "mime": mime
    }

    if level > 0 and path.is_dir():
        for file in path.iterdir():
            populate_info_dict(info, file, level - 1)

    return info


@cache_control(no_cache=True)
@require_safe
@require_path_exists
@condition(etag_func=get_path_etag, last_modified_func=get_path_last_mod)
def api_info(request: HttpRequest, path: Path):
    if request.method == "HEAD":
        return HttpResponse(status=200)

    level = int(request.GET.get("level", 0))
    return JsonResponse(populate_info_dict({}, fs_root / path, level))


@require_http_methods(["POST"])
@require_path_exists
def api_move(request: HttpRequest, src: Path):
    dst = request.body.decode('utf-8')

    if (r := check_permissions(request, dst)) is not None:
        return r

    full_src = fs_root / src
    full_dst = fs_root / dst

    if full_dst.exists():
        return HttpResponse(f"The file at {dst} already exists", status=400, content_type="text/plain;charset=utf-8")

    full_dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(full_src, full_dst)

    return HttpResponse(status=200)


@require_http_methods(["POST"])
def api_new(request: HttpRequest, path: Path):
    full_path = fs_root / path

    if full_path.exists():
        return HttpResponse(f"The file at {path} already exists", status=400)
    else:
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.touch()
        return HttpResponse(status=201)


@require_http_methods(["POST"])
def api_mkdir(request: HttpRequest, path: Path):
    full_path = fs_root / path

    if full_path.exists():
        return HttpResponse(f"The file at {path} already exists", status=400)
    else:
        full_path.mkdir(parents=True)
        return HttpResponse(status=201)


@require_http_methods(["POST"])
@require_path_exists
def api_rmdir(request: HttpRequest, path: Path):
    full_path = fs_root / path

    full_path.rmdir()
    return HttpResponse(status=200)


class api_class:
    @classmethod
    def dispatch(cls, request: HttpRequest, *args):
        match request.method:
            case "HEAD":
                return cls.get_or_head(request, *args, False)
            case "GET":
                return cls.get_or_head(request, *args, True)
            case "POST":
                return cls.post(request, *args)
            case _:
                log.error("Well, I forgot something again")
                return HttpResponse(status=500)


class FileHasher:
    def __init__(self, path: Path, buffer_size: int = 2 ** 16):
        self.path = path
        self.buffer_size = buffer_size

    def __enter__(self):
        self.buffer = bytearray(self.buffer_size)
        self.memory_view = memoryview(self.buffer)
        self.fp = open(self.path, "rb", buffering=0)
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.fp.close()

    def hash(self, start, length, debug=False):
        if debug:
            hsh = []
        else:
            hsh = hashlib.sha256()
        self.fp.seek(start, os.SEEK_SET)

        while n := self.fp.readinto(self.memory_view):
            memory = self.memory_view[:min(length, n)]
            if debug:
                hsh.append(memory.tobytes().decode())
            else:
                hsh.update(memory)
            length -= n

        if debug:
            return hsh
        else:
            return hsh.hexdigest()


class api_raw(api_class):
    @classmethod
    def get_or_head(cls, request: HttpRequest, path: Path, is_get: bool):
        full_path = fs_root / path

        if full_path.is_file():
            return FileResponse(open(full_path, "rb"), content_type=get_mime_type(full_path))
        else:
            files = list(full_path.iterdir())
            files.sort()
            files = [*filter(lambda f: not f.is_file(), files),
                     *filter(lambda f: f.is_file(), files)]
            files = {p.name: str(p.relative_to(fs_root)) for p in files}

            return JsonResponse(files)

    @classmethod
    def post(cls, request: HttpRequest, path: Path):
        full_path = fs_root / path

        if not full_path.is_file():
            raise UserError(f"Cannot write to {path}; is a directory")

        full_path.write_bytes(request.body)

        return HttpResponse(status=200)

    @staticmethod
    @cache_control(no_cache=True)
    @require_http_methods(["GET", "POST", "HEAD"])
    @require_path_exists
    @condition(etag_func=get_path_etag, last_modified_func=get_path_last_mod)
    def call(request: HttpRequest, path: Path):
        cls = api_raw
        return cls.dispatch(request, path)


class api_file_ledger(api_class):
    @classmethod
    def get_or_head(cls, request: HttpRequest, path: Path, is_get: bool):
        full_path = fs_root / path

private/templates/private/audio_view.html
{% extends "base.html" %}
{% load utils %}

{% block head %}
    {% load_css "navigation" %}
    {#    {% load_css "files/simple_table" %}#}
    {% include "private/common.html" %}

    <title x-data x-text="name">{{ name }}</title>

    <script>
        const current_path = "{{ parent }}";
        const name = "{{ name }}";
        const csrf_token = "{{ csrf_token }}";
    </script>
    <style>
        .center {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 20px;
        }
    </style>

    {% load_alpine %}
{% endblock %}

{% block content %}
    <div class="center">
        <audio x-data controls :src="api_url('raw', current_path + '/' + name)"

               style="width: 90vw; border: 1px solid black" preload="metadata">

        </audio>
    </div>
{% endblock %}

private/templates/private/cascade.html
{% extends "base.html" %}
{% load utils %}

{% block head %}
    {% load_css "navigation" %}
    {% load_css "files/cascade" %}
    {% include "private/common.html" %}

    <script>
        const current_path = "{{ path }}";
        const csrf_token = "{{ csrf_token }}";
        const images_per_page = 30;

        window.addEventListener("alpine:init", () => {
            Alpine.store("files", Alpine.reactive([]));
            Alpine.store("page", 1);
        });

        function get_images() {
            return Alpine.store("files")
                .filter(f => f.type !== '' && image_mime_re.test(f.type));
        }

        function get_current_images() {
            const page = Alpine.store("page");
            const index = (page - 1) * images_per_page;
            return get_images()
                .slice(index, index + images_per_page);
        }

        function page_count() {
            return Math.ceil(get_images().length / images_per_page)
        }

        function change_page(offset) {
            const count = page_count();
            let new_page = Alpine.store("page") + offset;
            if (new_page < 1) new_page = 1;
            else if (new_page > count) new_page = count;

            Alpine.store("page", new_page);
        }
    </script>

    {% load_alpine %}
    {% load_js "files/load_files" extra_args="defer" %}
    {% load_js "files/add_metadata" extra_args="defer" %}
{% endblock %}
{% block content_container %}
    <header x-data>
        <a :href="api_url('files', current_path)">Back to overview</a>
        Page: <span x-text="$store.page"></span>/<span x-text="page_count()"></span>
        <span x-show="page_count() > 1">
            <button @click="change_page(-1)"
                    @keyup.left.window.prevent="change_page(-1)">Previous
            </button>
            <button @click="change_page(1)"
                    @keyup.right.window.prevent="change_page(1)">Next
            </button>
        </span>
        <!-- Experiment for dynamic include_subdirectories -->
        <!--<label>
            <input type="checkbox" x-data x-model.boolean="$store.include_subdirectories">
            Include Subdirectories
        </label>-->
    </header>
    <main>
        <ul class="cascade">
            <template x-data x-for="file of get_current_images()">
                <li class="cascade">
                    <a class="cascade" :href="api_url('files', file.path)">
                        <img class="cascade"
                             alt="" :alt="file.name" src="" :src="api_url('raw', file.path)">
                    </a>
                </li>
            </template>
        </ul>
    </main>
{% endblock %}

private/templates/private/common.html
<script>
    function api_url(api, path = null, query = null) {
        let url = "{% url "private:ffs" %}" + api;

        if (path !== null) {
            url += "/" + encodeURIComponent(path);
        }

        if (query !== null) {
            url += "?" + query;
        }

        return url;
    }
</script>

private/templates/private/file_404.html
{# Send this if a file cannot be found on the ffs #}
{% extends "base.html" %}
{% load utils %}

{% block head %}
    {% load_css "navigation" %}
{% endblock %}

{% block content %}
    <h1>
        Hello, {{ request.user }}
    </h1>

    <h3>The file "{{ path }}" does not exist</h3>
{% endblock %}

private/templates/private/files.html
{% extends "base.html" %}
{% load utils %}

{% block head %}
    {% load_css "navigation" %}
    {% load_css "files/file_viewer" %}

    {% include "private/common.html" %}
    {% load_alpine %}
    {% load_js "files/load_files" extra_args="defer" %}
    {% load_js "files/add_metadata" extra_args="defer" %}
    {% load_js "files/upload" extra_args="defer" %}
    {% load_js "files/actions" extra_args="defer" %}
{% endblock %}

{% block content %}
    <h1 style="margin-bottom: 0;">
        Hello, {{ request.user }}
    </h1>
    <span><strong>Menu:</strong>
        <button class="custom-button"
                :class="$store.tab=='view' && 'selected'"
                x-data
                @click="$store.tab='view'"
                @keyup.v.window="$store.tab='view'">View</button>
          <button class="custom-button"
                  :class="$store.tab=='upload' && 'selected'"
                  x-data
                  @click="$store.tab='upload'"
                  @keyup.u.window="$store.tab='upload'">Upload</button>
        <a x-data :href="api_url('cascade', current_path)">Image Cascade</a></span>

    <div id="file_view_container" class="tab-container" x-data x-cloak x-show="$store.tab=='view'">
        <table id="file_view" cellspacing="0">
            <thead>
            <tr>
                <th><input
                        type="checkbox"
                        x-effect="$el.checked = $store.files.every(f=>f.selected)"
                        @change="$store.files.forEach(f=>f.selected=$el.checked)"></th>
                <th></th>
                <th>Name</th>
                <th>Type</th>
                <th>Size</th>
                <th>Actions</th>
            </tr>
            <tr class="thin-row">
                <th class="thin-row" colspan="6" style="text-align: left">
                    <button class="custom-button" @click="new_file()">New File
                    </button>
                    <button class="custom-button" @click="new_dir()">
                        New Folder
                    </button>
                    <button class="custom-button" x-text="'Move '+count_selected()+' Files'"
                            @click="move_files()">
                    </button>
                    <button class="custom-button" x-text="'Delete '+count_selected()+' Files'"
                            @click="delete_files()">
                    </button>
                </th>
            </tr>
            </thead>
            <tbody class="alternate-container">
            <template x-data x-for="file in $store.files">
                <tr class="alternate" :class="file.selected && 'selected'" @click.self="file.selected = !file.selected">
                    <td @click.self="file.selected = !file.selected">
                        <input type="checkbox" x-model="file.selected">
                    </td>
                    <td @click.self="file.selected = !file.selected" x-html="file.icon"></td>
                    <td @click.self="file.selected = !file.selected"><a :href="api_url('files', file.path)"
                                                                        x-text="file.name"></a></td>
                    <td @click.self="file.selected = !file.selected" x-text="file.type"></td>
                    <td @click.self="file.selected = !file.selected" x-text="file.size" style="text-align: right"></td>
                    <td @click.self="file.selected = !file.selected">
                        <button @click="rename_file(file)">Rename</button>
                        <button x-show="file.type === 'application/zip'"
                                @click="unzip(file.path)">Unzip
                        </button>
                    </td>
                </tr>
            </template>
            </tbody>
        </table>
    </div>
    <div id="upload_container" class="tab-container" style="margin-top: 20px" x-data x-cloak
         x-show="$store.tab=='upload'">
        <form id="file_input_container"
              @submit.prevent="upload_files_from($refs.files)"
              @keyup.alt.u.window.prevent="upload_files_from($refs.files)">
            <strong style="display: block">Direct File Upload:</strong>
            <label for="file-input">
                File to upload:
            </label>
            <input type="file" multiple x-ref="files"
                   @keyup.shift.u.window.prevent="$el.click()">
            <button style="display: block">Upload file</button>
        </form>
        <div id="status_messages" class="alternate-container">
            <template x-for="msg in $store.status">
                <div>
                    {# Here are all the different possible status messages #}
                    <template x-if="msg.type == 'plain'">
                        <div x-text="msg.content" class="status-message"></div>
                    </template>
                    <template x-if="msg.type != 'plain'">
                        <div class="status-message">
                            Uploading file "<span x-text="msg.upload.name"></span>" to
                            "<span x-text="msg.upload.path"></span>".
                            <span x-text="msg.upload.percentage"></span> completed.
                            <span x-text="msg.upload.finalisation_msg"></span>
                            <div style="display: flex; flex-wrap: wrap">
                                <template x-for="packet in msg.upload.packets">
                                    <span class="dot" :style="'background-color:'+packet.color"></span>
                                </template>
                            </div>
                        </div>
                    </template>
                </div>
            </template>
        </div>
    </div>

    <script>
        const current_path = "{{ path }}";
        const net_block_size = {{ net_block_size }};
        const csrf_token = "{{ csrf_token }}";

        document.addEventListener("alpine:init", () => {
            Alpine.store("tab", "view")
            Alpine.store("files", [])
            Alpine.store("status", [])
        })

        function count_selected() {
            return Alpine.store("files").filter(f => f.selected).length;
        }
    </script>

{% endblock %}

private/templates/private/image_view.html
{% extends "base.html" %}
{% load utils %}

{% block head %}
    {% load_css "navigation" %}
    {% load_css "files/simple_table" %}
    {% include "private/common.html" %}

    <title x-data x-text="get_name()">{{ name }}</title>

    <script>
        const current_path = "{{ parent }}";
        const name = "{{ name }}";
        const csrf_token = "{{ csrf_token }}";

        function get_images() {
            return Alpine.store("files")
                .filter(f => f.type !== '' && image_mime_re.test(f.type));
        }

        function get_name() {
            const files = get_images();
            const index = Alpine.store("index");
            if (index >= files.length) return name;
            else return files[Alpine.store("index")].name;
        }

        function load_current_exif() {
            const index = Alpine.store("index");
            const exif = Alpine.store("exif");

            exif[index] = Alpine.reactive({});
            document.dispatchEvent(new CustomEvent("loadexif", {detail: {name: get_name(), to: exif[index]}}))
        }

        function current_exif() {
            if (!Alpine.store("true_index"))
                return {};

            const index = Alpine.store("index");
            const exif = Alpine.store("exif");

            if (!exif.hasOwnProperty(index)) {
                load_current_exif();
            }
            return exif[index];
        }

        window.addEventListener("alpine:init", () => {
            Alpine.store("files", Alpine.reactive([]));
            Alpine.store("index", 0);
            Alpine.store("exif", Alpine.reactive({}));
            Alpine.store("true_index", false);
        });

    </script>
    <style>
        .center {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .space-before {
            margin-top: 20px;
        }

        button {
            margin: 5px;
        }
    </style>
    {% load_alpine %}
    {% load_js "files/load_files" extra_args="defer" %}
    {% load_js "files/add_metadata" extra_args="defer" %}
    {% load_js "files/actions" extra_args="defer" %}
    {% load_js "files/image_view" extra_args="defer" %}
{% endblock %}

{% block content %}
    <div x-data class="center" style="margin: 0 10px">
        <button @click="change(-1)"
                @keyup.left.window="change(-1)"
                x-show="$store.index > 0">
            Previous
        </button>
        <span x-text="$store.index + 1"></span> /
        <span x-text="get_images().length"></span>
        <button @click="change(1)"
                @keyup.right.window="change(1)"
                x-show="$store.index+1 < get_images().length">
            Next
        </button>
    </div>
    <div x-data class="center" style="margin: 0 10px">
        <button x-text="'Delete '+get_name()"
                @click="delete_current()"
                @keyup.delete.window.prevent="delete_current()">Delete
        </button>
    </div>
    <div class="center">
        <a x-data :href="api_url('raw', current_path + '/' + get_name())" style="width: 90vw; border: 1px solid black">
            <img alt="" src=""
                 x-data :alt="name" :src="api_url('raw', current_path + '/' + get_name())" style="width: 100%">
        </a>
    </div>
    <div class="space-before" x-data x-show="$store.true_index && Object.entries(current_exif()).length > 0">
        <table>
            <caption>Metadata</caption>
            <thead>
            <tr>
                <td>Name</td>
                <td>Value</td>
            </tr>
            </thead>
            <tbody>
            <template x-data x-for="entry in Object.entries(current_exif())">
                <tr>
                    <td x-text="entry[0]"></td>
                    <td x-text="entry[1]"></td>
                </tr>
            </template>
            </tbody>
        </table>
    </div>
{% endblock %}