dev/urls.py
from django.urls import path

from . import views

app_name = "dev"
urlpatterns = [
    path("", views.view_index, name="index"),
    path("headers", views.view_headers, name="headers"),
    path("log/<slug:service>/<slug:name>", views.view_log, name="log"),
]

guenthner_xyz/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, include

from general import plain_redirect, get_default_context, MySitemap
from . import views

error_urls = [path("", lambda *args: plain_redirect("/")),
              path("<int:status_code>", views.error_page), ]

account_urls = [path("login", LoginView.as_view(template_name="special/login.html",
                                                extra_context={**get_default_context(None),
                                                               "suppress_navbar": True,
                                                               "title": "Login to guenthner.xyz"}, ), name="login"),
                path("logout", LogoutView.as_view(template_name="special/logout.html",
                                                  extra_context={**get_default_context(None),
                                                                 "suppress_navbar": True,
                                                                 "title:": "You have been logged out"}, ),
                     name="logout")
    ,
                path("change-password",
                     PasswordChangeView.as_view(template_name="special/change_password.html",
                                                success_url=settings.PASSWORD_CHANGE_DONE_URL,
                                                extra_context={**get_default_context(None),
                                                               "suppress_navbar": True,
                                                               "title": "Change your password for guenthner.xyz"}, ),
                     name="change-password"),
                path("change-password/done",
                     PasswordChangeDoneView.as_view(template_name="special/change_password_done.html",
                                                    extra_context={**get_default_context(None),
                                                                   "suppress_navbar": True,
                                                                   "title": "Changing your password successful"}, ),
                     name="change-password-done")
                ]

indexed_routes = "index,math,eratosthenes,mandelbrot,paper,pretty,words,pictures,memes,creations,chat,cowsay,convolutions".split(",")

debug_static_routes = []

if settings.DEBUG:
    debug_static_routes = [path("js/<path:path>", views.view_debug_static("text/js")),
                           path("css/<path:path>", views.view_debug_static("text/css")), ]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(account_urls)),
    path("", include(debug_static_routes)),
    path("dev/", include("dev.urls")),
    path("private/", include("private.urls")),
    path("", include("root.urls")),
    path("error/", include(error_urls)),
    path("favicon.ico", lambda *args: plain_redirect("/images/site/icon.png", True)),
    MySitemap.with_path("sitemap.xml",
                        *[f"root:{i}" for i in indexed_routes]),

]

root/urls.py
from django.urls import path, include

from . import views

app_name = "root"

creations_urls = [path("", views.view_creations, name="creations"),
                  path("chat", views.view_chat, name="chat"),
                  path("cowsay", views.view_cowsay, name="cowsay"),
                  path("convolutions", views.view_convolutions, name="convolutions"),]

pretty_urls = [path("", views.view_pretty, name="pretty"),
               path("words", views.view_words, name="words"),
               path("pictures", views.view_pictures, name="pictures"), ]

math_urls = [path("", views.view_math, name="math"),
             path("paper", views.view_paper, name="paper"),
             path("mandelbrot", views.view_mandelbrot, name="mandelbrot"),
             path("eratosthenes", views.view_eratosthenes, name="eratosthenes")]

urlpatterns = [
    path("", views.view_index, name="index"),
    path("math/", include(math_urls)),
    path("pretty/", include(pretty_urls)),
    path("memes", views.view_memes, name="memes"),
    path("creations/", include(creations_urls)),
]

root/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import SET_NULL


class GlobalPermission(models.Model):
    # no fields needed; optional descriptive field
    name = models.CharField(max_length=128, blank=True)

    class Meta:
        verbose_name = "Global Permissions"
        verbose_name_plural = "Global Permissions"
        permissions = [
            ("admin", "Admin functions"),
        ]


class ChatMessage(models.Model):
    message = models.TextField()
    user = models.ForeignKey(User, on_delete=SET_NULL, null=True)
    time = models.DateTimeField(auto_now_add=True)

root/views.py
import math
import os
from datetime import datetime, UTC
from functools import reduce
from pathlib import Path

from django.conf import settings
from django.http import HttpRequest, HttpResponse
from django.views.decorators.cache import never_cache, cache_control
from django.views.decorators.http import condition

from general import default_render
from general.cowsay import run_cowsay
from root.models import ChatMessage

server_root = Path("/var/www/guenthner.xyz")


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_index(request: HttpRequest):
    return default_render(request, "root/index.html", {
        "first_name": "Jonathan",
        "last_name": "Günthner",
        "title": "Günthner's Webpage",
        "semester": int(math.ceil((datetime.now() - datetime(2024, 4, 1)).total_seconds() / (6 * 30 * 24 * 60 * 60))),
        "is_family": request.user.is_authenticated and request.user.has_perm("private.ffs")
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_pretty(request: HttpRequest):
    return default_render(request, "root/pretty/pretty.html", {
        "title": "Pretty Stuff I made"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_words(request: HttpRequest):
    return default_render(request, "root/pretty/words.html", {
        "title": "Pretty Words I wrote",
        "docs": os.listdir(server_root / "documents" / "stories"),
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_pictures(request: HttpRequest):
    return default_render(request, "root/pretty/pictures.html", {
        "title": "Pretty Pictures I made",
        "images": {"Sunlight.png": "A pretty abstract pictures with the theme sunlight",
                   "Sunlight - Pixelated.png": "The previous picture, but more pixelated",
                   "Blurry Sundown.png": "A blurry sundown recorded above a highway in Augsburg",
                   "Blurrier Sundown.png": "A blurrier version of the previous image"}
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_memes(request: HttpRequest):
    return default_render(request, "root/memes.html", {
        "title": "Memes",
        "images": os.listdir(server_root / "images" / "memes"),
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_creations(request: HttpRequest):
    return default_render(request, "root/creations/creations.html", {
        "title": "Creations"
    })


@never_cache
def view_cowsay(request: HttpRequest):
    return default_render(request, "root/creations/cowsay.html", {
        "title": "Cowsay",
        "output": run_cowsay()
    })


@never_cache
def view_chat(request: HttpRequest):
    error_msg = None
    messages = ChatMessage.objects.all()

    if request.method == "POST":
        if request.POST["message"] is None:
            error_msg = "No message received by server"
        elif request.POST["message"].strip() == "":
            error_msg = "Empty message"
        elif len(messages) > 0:
            last_msg_time = reduce(max, [m.time for m in messages])
            delta = (datetime.now(tz=UTC) - last_msg_time).total_seconds()
            if delta < 10:
                error_msg = "Wait at least 10 seconds between messages"

        if error_msg is None:
            ChatMessage.objects.create(user=request.user if request.user.is_authenticated else None,
                                       message=request.POST["message"], )

        if request.POST.get("FROM_JS", False):
            return HttpResponse(error_msg, status=200 if error_msg is None else 400)

    return default_render(request, "root/creations/chat.html", {
        "title": "Chat",
        "messages": messages,
        "error_msg": error_msg})


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_convolutions(request: HttpRequest):
    return default_render(request, "root/creations/convolutions.html", {
        "title": "Convolutions",
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_math(request: HttpRequest):
    return default_render(request, "root/math/math.html", {
        "title": "The Math-Corner"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_paper(request: HttpRequest):
    return default_render(request, "root/math/paper.html", {
        "title": "Paper"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_mandelbrot(request: HttpRequest):
    return default_render(request, "root/math/mandelbrot.html", {
        "title": "Mandelbrot"
    })


@cache_control(max_age=settings.CACHE_MIDDLEWARE_SECONDS)
@condition(etag_func=lambda *a, **kw: "A")
def view_eratosthenes(request: HttpRequest):
    return default_render(request, "root/math/eratosthenes.html", {
        "title": "Eratosthenes"
    })

root/templates/root/index.html
{% extends "base.html" %}
{% load utils %}
{% load humanize %}
{% block head %}
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "Person",
            "name": "{{ first_name }} {{ last_name }}",
            "familyName": "{{ last_name }}",
            "givenName": "{{ first_name }}",
            "affiliation": {
                 "@type": "CollegeOrUniversity",
                 "name": "University of Augsburg",
                 "sameAs": "https://en.wikipedia.org/wiki/University_of_Augsburg"
            },
            "email": "j@guenthner.xyz"
        }
    </script>

    {{ "The personal Webpage of Jonathan Günthner. I am a mathematician at the University in Augsburg, I also like to code hence this website."|add_description }}
    {% load_css "navigation" %}
    {% load_css "random_math_field" %}
    <!-- KaTeX here -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.css"
          integrity="sha384-o3WH+1yEhq+grOgz1BVYTZPyTlMXrDxnjN1By9/ba94JqJhva6wFm2Hb+URQX53v" crossorigin="anonymous">
    <script id="katex-script" defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.js"
            integrity="sha384-C5yZTsgLOfuizO9kb+hrB8uSBwwvZ4yenKWU0KmWl+7bkL6Tph/KbcOa3S4zdoRE"
            crossorigin="anonymous"></script>
    <style>
        div {
            margin-bottom: 6px;
        }

        .opti-bold {
            color: black;
            text-decoration: none;
            font-weight: bolder;
        }

        .opti-bold:hover {
            text-decoration: black underline;
        }

        .rainbow-text {
            font-weight: bolder;
            background-image: linear-gradient(90deg, red, orange, yellow, green, blue, violet);
            color: transparent;
            -webkit-background-clip: text;
            filter: brightness(80%);
        }

        .accessibility-only {
            position: absolute;
            left: -10000px;
            top: auto;
            width: 1px;
            height: 1px;
            overflow: hidden;
        }

        pre {
            font: inherit
        }

        .barely-visible {
            opacity: 80%;
        }

        .plain-link {
            text-decoration: none;
            color: black;
        }
    </style>
{% endblock %}
{% block content %}
    <h1>The personal webpage of {{ first_name }} {{ last_name }}
    </h1>
    <div>
        I am a mathematician that likes to code
        <span class="barely-visible">
        (and a <a class="plain-link" href="https://de.wikipedia.org/wiki/Eichh%C3%B6rnchen">squirrel</a>).
    </span>
    </div>
    <div>
        I am currently stu<a class="opti-bold" href="https://en.wikipedia.org/wiki/Pun">dying</a> in
        my {{ semester|ordinal }} semester at the university in <a
            href="https://en.wikipedia.org/wiki/Beauty">Augsburg</a> and struggling with
        <a class="rainbow-text" href="https://en.wikipedia.org/wiki/Depression_(mood)">depression</a>. Perhaps
        the <span class="random-math-field" data-singular="<FIELD> has" data-plural="<FIELD> have">algebra has</span>
        gotten
        to me...
    </div>
    <div>
        Did you know that
        <a class="plain-link latex" href="https://guenthner.xyz/math/paper">\newcommand{\ord}{\mathop{\text{ord}}}
            \ord_{p^k}(m) = \ord_{p}(m) \cdot p^{\max(0, k - k_0 + 1)}</a>
        for
        <a class="plain-link latex" href="https://en.wikipedia.org/wiki/2">p\not=2</a>?
    </div>
    <div>
        <pre>
Kind regards,
J. {{ last_name }}</pre>
    </div>
    <div>
        <pre>
P.S.:
Here are a couple of links:</pre>
        <ul class="navigation">
            <li><a href="{% url 'root:math' %}">Math</a></li>
            <li><a href="{% url 'root:pretty' %}">Pretty</a></li>
            <li><a href="{% url 'root:memes' %}">Memes</a></li>
            <li><a href="{% url 'root:creations' %}"
                   style="font-family: monospace; padding: 6px 1px 4px 1px">Creations</a></li>
            <li>My Mail Address: <a href="mailto:j@guenthner.xyz">j@guenthner.xyz</a></li>
            <li>My github: <a href="https://github.com/Askhor">Askhor</a></li>
            <li style="display: none"><a rel="me" href="https://mastodon.social/@guenthner">Mastodon</a></li>
            <li>My <a href="https://guenthner.xyz/info/J. Günthner - Key.gpg" download>GPG Public Key</a></li>
            {% if is_family %}
                <li><a href="{% url "root:index" %}private">FFS</a> (you are logged in as {{ user }})</li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

{% block post %}
    {% load_js "random_math_field" %}
    <script>
        document.getElementById("katex-script").addEventListener("load", _ => {
            console.log("Rendering LaTeX");
            document.querySelectorAll(".latex").forEach(el => {
                katex.render(el.textContent, el);
            })
        })
    </script>
{% endblock %}

root/templates/root/memes.html
{% extends "base.html" %}
{% load utils %}
{% block head %}
    {{ "Just some memes"|add_description }}
    {% load_css "navigation" %}
    {% load_css "image_formatting" %}
{% endblock %}
{% block content %}
    <h1>Just some memes</h1>
    <div>
        {% for img in images %}
            <a href='https://{{ request.get_host }}/images/memes/{{ img }}'><img
                    src='https://{{ request.get_host }}/images/memes/{{ img }}'
                    alt='{{ img|strip_file_extension }}'></a>
        {% endfor %}
    </div>
{% endblock %}